language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

cache: pip

install:
    - pip install -q -U pip codecov coveralls coverage
    - pip install .

script:
    - nosetests --with-coverage --cover-package=defang

after_success:
    - coveralls
    - codecov

